# yaml-language-server: $schema=https://json-schema.org/draft-07/schema

title: TerraformProjectConfiguration
type: object
description: Refinement of the project configuration with the known Terraform language.
properties:
  project:
    type: object
    properties:
      language:
        anyOf:
          - type: string

          - title: TerraformLanguage
            type: string
            enum:
              - terraform
            description: A Terraform project.
