// This file was generated by the Causa command line. Do not edit it manually.

import { AllowMissing } from '@causa/workspace/validation';
import { Type } from 'class-transformer';
import { IsObject, IsString, ValidateNested } from 'class-validator';

/**
 * Configuration for Terraform.
 */
export class Terraform {
  constructor(init: Terraform) {
    Object.assign(this, init);
  }

  /**
   * The Terraform workspace that should be selected prior to performing `plan` and `apply` operations.
   */
  @AllowMissing()
  @IsString()
  readonly workspace?: string;

  /**
   * The version of Terraform to use.
   * Can be a semver version, or `latest`.
   * The installed version is considered compatible if it is greater than or equal to the configured version, within the same major version.
   */
  @AllowMissing()
  @IsString()
  readonly version?: string;

  [key: string]: any;
}

/**
 * The schema for the Terraform configuration.
 */
export class TerraformConfiguration {
  constructor(init: TerraformConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Configuration for Terraform.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => Terraform)
  @ValidateNested()
  readonly terraform?: Terraform;

  [key: string]: any;
}

/**
 * A Terraform project.
 */
export enum TerraformLanguage {
  Terraform = 'terraform',
}

export type Language = string | TerraformLanguage;

export class Project {
  constructor(init: Project) {
    Object.assign(this, init);
  }

  @AllowMissing()
  readonly language?: Language;

  [key: string]: any;
}

/**
 * Refinement of the project configuration with the known Terraform language.
 */
export class TerraformProjectConfiguration {
  constructor(init: TerraformProjectConfiguration) {
    Object.assign(this, init);
  }

  @AllowMissing()
  @IsObject()
  @Type(() => Project)
  @ValidateNested()
  readonly project?: Project;

  [key: string]: any;
}
