// This file was generated by the Causa command line. Do not edit it manually.

import { AllowMissing } from '@causa/workspace/validation';
import { IsString } from 'class-validator';

/**
 * Configuration for Terraform.
 */
export class Terraform {
  constructor(init: Terraform) {
    Object.assign(this, init);
  }

  /**
   * The version of Terraform to use.
   * Can be a semver version, or `latest`.
   * The installed version is considered compatible if it is greater than or equal to the configured version, within the same major version.
   */
  @AllowMissing()
  @IsString()
  readonly version?: string;

  /**
   * The Terraform workspace that should be selected prior to performing `plan` and `apply` operations.
   */
  @AllowMissing()
  @IsString()
  readonly workspace?: string;
  [property: string]: any;
}

/**
 * The schema for the Terraform configuration.
 */
export class TerraformConfiguration {
  constructor(init: TerraformConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Configuration for Terraform.
   */
  @AllowMissing()
  readonly terraform?: Terraform;
  [property: string]: any;
}
